services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - n8n_net

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - '5678:5678'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    mem_limit: 2g
    memswap_limit: 2g
    environment:
      - N8N_HOST=78.47.110.193
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_FUNCTION_ALLOW_BUILTIN=fs,path,crypto,child_process
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_RUNNERS_HEARTBEAT_INTERVAL=60
      - N8N_RUNNERS_TASK_TIMEOUT=300
      - N8N_RUNNERS_MAX_OLD_SPACE_SIZE=1536
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
    volumes:
      - ./n8n_data:/home/node/.n8n
      - /data:/data
    networks:
      - n8n_net
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_net

networks:
  n8n_net:
    driver: bridge
